# models/job_requirement.py
# ─────────────────────────────────────────────────────────────
# SQLAlchemy ORM model for the `job_requirements` table.
# Each instance of this class maps to one row in the table.
# ─────────────────────────────────────────────────────────────

from datetime import datetime
from sqlalchemy import (
    Column,
    Integer,
    String,
    Date,
    Numeric,
    DateTime,
    Enum as SAEnum,
    func,
)
from app.core.database import Base


class JobRequirement(Base):
    """
    Represents one job requirement posted by the recruiter.
    Table name: job_requirements
    """

    __tablename__ = "job_requirements"

    # ── Primary Key ───────────────────────────────────────────
    id = Column(Integer, primary_key=True, index=True, autoincrement=True)

    # ── Business Key ─────────────────────────────────────────
    # Unique, human-readable code generated by the service layer.
    # Format: JOB-0001, JOB-0002, …
    job_code = Column(String(20), unique=True, nullable=False, index=True)

    # ── Core Fields ───────────────────────────────────────────
    job_date = Column(Date, nullable=False)

    # VARCHAR(255) is safe for company/title strings
    company_name = Column(String(255), nullable=False)
    job_title = Column(String(255), nullable=False)

    # How many candidates are required for this position
    candidates_required = Column(Integer, nullable=False)

    # Free-form text like "3-5 years" or "Fresher"
    experience_required = Column(String(100), nullable=False)

    # Budget as a string like "18-22 LPA" (keeps it flexible)
    budgeted_package = Column(String(100), nullable=False)

    # Name of the recruiter assigned to this requirement
    assigned_recruiter = Column(String(255), nullable=False)

    # Status of the requirement
    status = Column(
        SAEnum("ACTIVE", "ON_HOLD", "CLOSED", "DRAFT", name="job_status_enum"),
        nullable=False,
        default="ACTIVE",
    )

    # ── Timestamps ────────────────────────────────────────────
    # server_default=func.now() lets MySQL set the value automatically.
    created_at = Column(DateTime, nullable=False, server_default=func.now())
    updated_at = Column(
        DateTime,
        nullable=False,
        server_default=func.now(),
        onupdate=func.now(),
    )

    def __repr__(self) -> str:
        return f"<JobRequirement id={self.id} code={self.job_code} title='{self.job_title}'>"
