# models/job_requirement.py
# ─────────────────────────────────────────────────────────────
# SQLAlchemy ORM model for the `job_requirements` table.
# Each instance of this class maps to one row in the table.
# ─────────────────────────────────────────────────────────────

from datetime import datetime
from sqlalchemy import (
    Column,
    Integer,
    String,
    Date,
    DateTime,
    Enum as SAEnum,
    func,
    ForeignKey,
)
from sqlalchemy.orm import relationship
from app.core.database import Base


class Job(Base):
    """
    Represents one job posted by the recruiter (Parent).
    Table name: jobs
    """

    __tablename__ = "jobs"

    # ── Primary Key ───────────────────────────────────────────
    id = Column(Integer, primary_key=True, index=True, autoincrement=True)

    # ── Business Key ─────────────────────────────────────────
    # Unique, human-readable code generated by the service layer.
    job_code = Column(String(20), unique=True, nullable=False, index=True)

    # ── Core Fields ───────────────────────────────────────────
    job_date = Column(Date, nullable=False)
    company_name = Column(String(255), nullable=False)
    
    # Name of the recruiter assigned to this requirement
    assigned_to = Column(String(255), nullable=False)

    # Status of the requirement
    status = Column(
        SAEnum("ACTIVE", "ON_HOLD", "CLOSED", "DRAFT", name="job_status_enum"),
        nullable=False,
        default="ACTIVE",
    )

    # ── Timestamps ────────────────────────────────────────────
    created_at = Column(DateTime, nullable=False, server_default=func.now())
    updated_at = Column(
        DateTime,
        nullable=False,
        server_default=func.now(),
        onupdate=func.now(),
    )

    # ── Relationships ──────────────────────────────────────────
    requirements = relationship("JobRequirement", back_populates="job", cascade="all, delete-orphan")

    def __repr__(self) -> str:
        return f"<Job id={self.id} code={self.job_code} company='{self.company_name}'>"


class JobRequirement(Base):
    """
    Represents one hiring requirement within a job.
    Table name: job_requirements
    """

    __tablename__ = "job_requirements"

    id = Column(Integer, primary_key=True, index=True, autoincrement=True)
    job_id = Column(Integer, ForeignKey("jobs.id", ondelete="CASCADE"), nullable=False)
    
    # MOVED FROM JOB
    job_title = Column(String(255), nullable=False)
    budget = Column(String(100), nullable=False)
    
    # ORIGINAL FIELDS
    experience = Column(String(100), nullable=False)
    num_candidates = Column(Integer, nullable=False)

    # Relationship back to current job
    job = relationship("Job", back_populates="requirements")

    def __repr__(self) -> str:
        return f"<JobRequirement id={self.id} job_id={self.job_id} title='{self.job_title}' exp='{self.experience}'>"


