from pydantic import BaseModel, ConfigDict, field_validator
from typing import Optional
import datetime as dt
import re
from enum import Enum


class EmployeeStatus(str, Enum):
    ACTIVE = "Active"
    INACTIVE = "Inactive"


class EmployeeBase(BaseModel):
    """
    Base properties shared across different employee schemas.
    """
    first_name: Optional[str] = None
    last_name: Optional[str] = None
    blood_group: Optional[str] = None
    gender: Optional[str] = None
    country_code: Optional[str] = None
    contact_number: Optional[str] = None
    email: Optional[str] = None
    permanent_address: Optional[str] = None
    current_address: Optional[str] = None
    designation: Optional[str] = None
    date_of_joining: Optional[dt.date] = None
    package: Optional[float] = None
    status: EmployeeStatus = EmployeeStatus.ACTIVE
    profile_status: Optional[str] = "Draft"
    completion_percentage: Optional[int] = 0
    profile_status_hr: Optional[str] = "Draft"
    completion_percentage_hr: Optional[int] = 0
    profile_status_admin: Optional[str] = "Draft"
    completion_percentage_admin: Optional[int] = 0
    last_working_date: Optional[dt.date] = None
    date: Optional[dt.date] = None

    # New fields
    date_of_birth: Optional[dt.date] = None
    countrycode_office_contact: Optional[str] = None
    contact_number_office: Optional[str] = None
    countrycode_emergency_contact: Optional[str] = None
    emergency_contact_number: Optional[str] = None
    aadhar_number: Optional[str] = None
    aadhar_url: Optional[str] = None
    pan_number: Optional[str] = None
    pan_url: Optional[str] = None
    marksheet_10th_url: Optional[str] = None
    marksheet_12th_url: Optional[str] = None
    marksheet_graduation_url: Optional[str] = None
    present_address_proof_url: Optional[str] = None
    permanent_address_proof_url: Optional[str] = None
    photo_url: Optional[str] = None
    medical_condition: Optional[str] = None
    resume_url: Optional[str] = None
    salary_slips_url: Optional[str] = None
    offer_letter_url: Optional[str] = None
    last_company_name: Optional[str] = None

    # Bank Details
    bank_name: Optional[str] = None
    bank_account_number: Optional[str] = None
    bank_ifsc_code: Optional[str] = None

    # Reporting & Compliance Details
    assigned_business_unit: Optional[str] = None
    reporting_to: Optional[str] = None
    reporting_designation: Optional[str] = None
    work_mode: Optional[str] = None
    ctc: Optional[float] = None
    compliance: Optional[str] = None
    system_role: Optional[str] = "unassigned"

    # Asset & System Configuration Details
    system_assigned: Optional[str] = None
    sim_card_assigned: Optional[str] = None
    email_id_configured: Optional[str] = None
    linkedin_configured: Optional[str] = None
    google_sheet_configured: Optional[str] = None
    whatsapp_business_configured: Optional[str] = None
    employee_password: Optional[str] = None

    # ─────────────────────────────────────────────────────────────
    # DUAL-LAYER BACKEND VALIDATORS
    # ─────────────────────────────────────────────────────────────

    @field_validator('contact_number', 'contact_number_office', 'emergency_contact_number', mode='before')
    @classmethod
    def validate_phone_numbers(cls, v):
        if v and str(v).strip():
            val = str(v).strip()
            if not re.match(r"^\d{10}$", val):
                raise ValueError("Phone number must be exactly 10 digits")
        return v

    @field_validator('aadhar_number', mode='before')
    @classmethod
    def validate_aadhar_number(cls, v):
        if v and str(v).strip():
            val = str(v).strip()
            if not re.match(r"^\d{12}$", val):
                raise ValueError("Aadhar number must be exactly 12 digits")
        return v

    @field_validator('pan_number', mode='before')
    @classmethod
    def validate_pan_number(cls, v):
        if v and str(v).strip():
            val = str(v).strip().upper()
            if not re.match(r"^[A-Z]{5}[0-9]{4}[A-Z]{1}$", val):
                raise ValueError("Invalid PAN format. Example: DAHPN8767B")
            return val
        return v

    @field_validator('bank_ifsc_code', mode='before')
    @classmethod
    def validate_ifsc_code(cls, v):
        if v and str(v).strip():
            val = str(v).strip().upper()
            if not re.match(r"^[A-Z]{4}0[A-Z0-9]{6}$", val):
                raise ValueError("Invalid IFSC code format (e.g. SBIN0001234)")
            return val
        return v


class EmployeeCreateRequest(EmployeeBase):
    """
    Schema for creating a new employee.
    Inherits all fields from EmployeeBase.
    (employee_id is auto-generated by the backend)
    """
    pass


class EmployeeUpdateRequest(BaseModel):
    """
    Schema for updating an existing employee.
    All fields are optional because the user might only update some of them.
    """
    first_name: Optional[str] = None
    last_name: Optional[str] = None
    blood_group: Optional[str] = None
    gender: Optional[str] = None
    country_code: Optional[str] = None
    contact_number: Optional[str] = None
    email: Optional[str] = None
    permanent_address: Optional[str] = None
    current_address: Optional[str] = None
    designation: Optional[str] = None
    date_of_joining: Optional[dt.date] = None
    package: Optional[float] = None
    status: Optional[EmployeeStatus] = None
    profile_status_hr: Optional[str] = None
    completion_percentage_hr: Optional[int] = None
    profile_status_admin: Optional[str] = None
    completion_percentage_admin: Optional[int] = None
    last_working_date: Optional[dt.date] = None
    date: Optional[dt.date] = None

    # New fields
    date_of_birth: Optional[dt.date] = None
    countrycode_office_contact: Optional[str] = None
    contact_number_office: Optional[str] = None
    countrycode_emergency_contact: Optional[str] = None
    emergency_contact_number: Optional[str] = None
    aadhar_number: Optional[str] = None
    aadhar_url: Optional[str] = None
    pan_number: Optional[str] = None
    pan_url: Optional[str] = None
    marksheet_10th_url: Optional[str] = None
    marksheet_12th_url: Optional[str] = None
    marksheet_graduation_url: Optional[str] = None
    present_address_proof_url: Optional[str] = None
    permanent_address_proof_url: Optional[str] = None
    photo_url: Optional[str] = None
    medical_condition: Optional[str] = None
    resume_url: Optional[str] = None
    salary_slips_url: Optional[str] = None
    offer_letter_url: Optional[str] = None
    last_company_name: Optional[str] = None

    # Bank Details
    bank_name: Optional[str] = None
    bank_account_number: Optional[str] = None
    bank_ifsc_code: Optional[str] = None

    # Reporting & Compliance Details
    assigned_business_unit: Optional[str] = None
    reporting_to: Optional[str] = None
    reporting_designation: Optional[str] = None
    work_mode: Optional[str] = None
    ctc: Optional[float] = None
    compliance: Optional[str] = None

    # Asset & System Configuration Details
    system_assigned: Optional[str] = None
    sim_card_assigned: Optional[str] = None
    email_id_configured: Optional[str] = None
    linkedin_configured: Optional[str] = None
    google_sheet_configured: Optional[str] = None
    whatsapp_business_configured: Optional[str] = None
    employee_password: Optional[str] = None


class EmployeeResponse(EmployeeBase):
    """
    Schema for returning employee data back to the frontend.
    Includes database-generated fields like id and employee_id.
    """
    id: int
    employee_id: str

    # This tells Pydantic to read data even if it's an ORM model (SQLAlchemy)
    # instead of a regular dictionary.
    model_config = ConfigDict(from_attributes=True)
