from pydantic import BaseModel, ConfigDict
from typing import Optional
from datetime import date, datetime
from enum import Enum


class EmployeeStatus(str, Enum):
    ACTIVE = "Active"
    INACTIVE = "Inactive"


class EmployeeBase(BaseModel):
    """
    Base properties shared across different employee schemas.
    """
    first_name: str
    last_name: str
    preferred_name: Optional[str] = None
    designation: str
    date_of_joining: date
    package: Optional[float] = None
    status: EmployeeStatus = EmployeeStatus.ACTIVE
    last_working_date: Optional[date] = None


class EmployeeCreateRequest(EmployeeBase):
    """
    Schema for creating a new employee.
    Inherits all fields from EmployeeBase.
    (employee_id is auto-generated by the backend)
    """
    pass


class EmployeeUpdateRequest(BaseModel):
    """
    Schema for updating an existing employee.
    All fields are optional because the user might only update some of them.
    """
    first_name: Optional[str] = None
    last_name: Optional[str] = None
    preferred_name: Optional[str] = None
    designation: Optional[str] = None
    date_of_joining: Optional[date] = None
    package: Optional[float] = None
    status: Optional[EmployeeStatus] = None
    last_working_date: Optional[date] = None


class EmployeeResponse(EmployeeBase):
    """
    Schema for returning employee data back to the frontend.
    Includes database-generated fields like id and employee_id.
    """
    id: int
    employee_id: str

    # This tells Pydantic to read data even if it's an ORM model (SQLAlchemy)
    # instead of a regular dictionary.
    model_config = ConfigDict(from_attributes=True)
