// Mock data for the Right Move CRM

export const mockJobs = [
  {
    id: 'JR-001',
    date: '2026-03-15',
    companyName: 'Infosys Technologies',
    jobTitle: 'Senior React Developer',
    numberOfCandidates: 5,
    experience: '4-6 years',
    budget: '₹18-22 LPA',
    assignedRecruiter: 'Priya Sharma',
    status: 'active',
  },
  {
    id: 'JR-002',
    date: '2026-03-18',
    companyName: 'TCS Digital',
    jobTitle: 'DevOps Engineer',
    numberOfCandidates: 3,
    experience: '3-5 years',
    budget: '₹15-20 LPA',
    assignedRecruiter: 'Rahul Mehta',
    status: 'active',
  },
  {
    id: 'JR-003',
    date: '2026-03-20',
    companyName: 'Wipro Ltd',
    jobTitle: 'Data Engineer',
    numberOfCandidates: 4,
    experience: '2-4 years',
    budget: '₹12-16 LPA',
    assignedRecruiter: 'Amit Verma',
    status: 'closed',
  },
  {
    id: 'JR-004',
    date: '2026-03-22',
    companyName: 'HCL Technologies',
    jobTitle: 'Product Manager',
    numberOfCandidates: 2,
    experience: '5-8 years',
    budget: '₹25-35 LPA',
    assignedRecruiter: 'Priya Sharma',
    status: 'active',
  },
  {
    id: 'JR-005',
    date: '2026-03-24',
    companyName: 'Cognizant',
    jobTitle: 'Java Backend Developer',
    numberOfCandidates: 6,
    experience: '3-5 years',
    budget: '₹14-18 LPA',
    assignedRecruiter: 'Neha Singh',
    status: 'on-hold',
  },
];

export const mockCandidates = [
  {
    id: 'CAN-001',
    firstName: 'Aditya',
    lastName: 'Kumar',
    countryCode: '+91',
    phone: '98765 43210',
    email: 'aditya.kumar@email.com',
    currentLocation: 'Bangalore',
    currentCompany: 'Mindtree Ltd',
    totalExperience: '5 years',
    relevantExperience: '4',
    highestEducation: 'B.Tech Computer Science',
    skills: ['React', 'Node.js', 'MongoDB', 'AWS'],
    currentCTC: '12',
    expectedCTC: '18',
    noticePeriod: '30 days',
    reasonForChange: 'Better growth opportunities',
    resumeFileName: 'aditya_kumar_resume.pdf',
    appliedDate: '2026-03-20',
  },
  {
    id: 'CAN-002',
    firstName: 'Sneha',
    lastName: 'Patel',
    countryCode: '+91',
    phone: '87654 32109',
    email: 'sneha.patel@email.com',
    currentLocation: 'Pune',
    currentCompany: 'Accenture',
    totalExperience: '3 years',
    relevantExperience: '3',
    highestEducation: 'MCA',
    skills: ['Python', 'Django', 'PostgreSQL', 'Docker'],
    currentCTC: '8',
    expectedCTC: '12',
    noticePeriod: '60 days',
    reasonForChange: 'Seeking remote opportunities',
    resumeFileName: 'sneha_patel_resume.pdf',
    appliedDate: '2026-03-21',
  },
  {
    id: 'CAN-003',
    firstName: 'Rohan',
    lastName: 'Desai',
    countryCode: '+91',
    phone: '76543 21098',
    email: 'rohan.desai@email.com',
    currentLocation: 'Mumbai',
    currentCompany: 'Mastech Digital',
    totalExperience: '7 years',
    relevantExperience: '6',
    highestEducation: 'B.E. Information Technology',
    skills: ['Java', 'Spring Boot', 'Kubernetes', 'Azure'],
    currentCTC: '18',
    expectedCTC: '25',
    noticePeriod: '90 days',
    reasonForChange: 'Higher compensation',
    resumeFileName: 'rohan_desai_resume.pdf',
    appliedDate: '2026-03-22',
  },
];

export const mockRecruiters = [
  { value: 'priya-sharma', label: 'Priya Sharma' },
  { value: 'rahul-mehta', label: 'Rahul Mehta' },
  { value: 'amit-verma', label: 'Amit Verma' },
  { value: 'neha-singh', label: 'Neha Singh' },
  { value: 'vikram-joshi', label: 'Vikram Joshi' },
];

export const mockDashboardStats = {
  openPositions: 24,
  candidates: 87,
  interviews: 12,
  offers: 5,
};

export const mockPipeline = [
  { stage: 'Sourcing', count: 87, percentage: 72 },
  { stage: 'Screening', count: 54, percentage: 55 },
  { stage: 'Interview', count: 28, percentage: 33 },
  { stage: 'Offer', count: 5, percentage: 8 },
];

export const mockRecentApplications = [
  {
    id: 'APP-001',
    candidateName: 'Aditya Kumar',
    jobTitle: 'Senior React Developer',
    company: 'Infosys Technologies',
    status: 'interview',
    date: '2026-03-25',
  },
  {
    id: 'APP-002',
    candidateName: 'Sneha Patel',
    jobTitle: 'DevOps Engineer',
    company: 'TCS Digital',
    status: 'screening',
    date: '2026-03-24',
  },
  {
    id: 'APP-003',
    candidateName: 'Rohan Desai',
    jobTitle: 'Java Backend Developer',
    company: 'Cognizant',
    status: 'offer',
    date: '2026-03-23',
  },
];
